language: php

matrix:
  fast_finish: true
  include:
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.3
      env: SUITE='server_data'
  allow_failures:
    - php: 7.3
      env: SUITE='server_data'

before_install:
  # Composer only updated in TravisCI containers when they build their images every month or so
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist

script:
- if [ -z "$SUITE" ]; then  vendor/bin/phpunit  --testsuite unit; fi;
- if [ "$SUITE" == "server_data" ]; then php -d default_socket_timeout=2 vendor/bin/phpunit  --testsuite server_data; fi;